package ejemplo;
// Generated 10-dic-2019 12:32:57 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "Address", catalog = "ejemploManyToMany")
public class Address implements java.io.Serializable {

	private long id;
	private String number;
	private String postalCode;
	private String street;

	public Address() {
	}

	public Address(long id) {
		this.id = id;
	}

	public Address(long id, String number, String postalCode, String street) {
		this.id = id;
		this.number = number;
		this.postalCode = postalCode;
		this.street = street;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "number")
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "postalCode")
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "street")
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

}
