package ejemplo;
// Generated 10-dic-2019 12:32:57 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PersonAddress generated by hbm2java
 */
@Entity
@Table(name = "PersonAddress", catalog = "ejemploManyToMany")
public class PersonAddress implements java.io.Serializable {

	private PersonAddressId id;

	public PersonAddress() {
	}

	public PersonAddress(PersonAddressId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "personId", column = @Column(name = "person_id", nullable = false)),
			@AttributeOverride(name = "addressId", column = @Column(name = "address_id", nullable = false)) })
	public PersonAddressId getId() {
		return this.id;
	}

	public void setId(PersonAddressId id) {
		this.id = id;
	}

}
