package ejemplo;
// Generated 10-dic-2019 12:32:57 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "Person", catalog = "ejemploManyToMany", uniqueConstraints = @UniqueConstraint(columnNames = "registrationNumber"))
public class Person implements java.io.Serializable {

	private long id;
	private String registrationNumber;

	public Person() {
	}

	public Person(long id) {
		this.id = id;
	}

	public Person(long id, String registrationNumber) {
		this.id = id;
		this.registrationNumber = registrationNumber;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "registrationNumber", unique = true)
	public String getRegistrationNumber() {
		return this.registrationNumber;
	}

	public void setRegistrationNumber(String registrationNumber) {
		this.registrationNumber = registrationNumber;
	}

}
